name: "Backend"

services:
  postgres:
    image: postgres:15
    container_name: movie_recommendation_db
    restart: always
    environment:
      POSTGRES_DB: movie_recommendation
      POSTGRES_USER: movieuser
      POSTGRES_PASSWORD: yomal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - movie_network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: movie_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@movieapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - movie_network

volumes:
  postgres_data:

networks:
  movie_network:
    driver: bridge
